---

- name: ensure iptables rules are installed
  copy: src="{{ item }}" dest=/etc/iptables backup=yes
  with_first_found:
    - files:
      - "{{ playbook_dir }}/assets/iptables_rules"
      - rules
  notify:
    - reload iptables

- name: ensure iptables added to autoload
  copy: src=autoload dest=/etc/network/if-pre-up.d/iptables mode=0755 backup=yes
