---

- name: ensure swap space is created
  command: dd if=/dev/zero of=/swapfile bs=1M count=1000
  when: ansible_swaptotal_mb < 1

- name: make swap
  command: mkswap /swapfile
  when: ansible_swaptotal_mb < 1

- name: ensure swap added to fstab
  lineinfile: dest=/etc/fstab regexp="swapfile" line="/swapfile none swap sw 0 0" state=present
  when: ansible_swaptotal_mb < 1

- name: ensure swap is turned on
  command: swapon -a
  when: ansible_swaptotal_mb < 1
