---

- name: ensure postgresql apt-key is added
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

- name: ensure postgresql repo is added
  apt_repository: repo="deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main" state=present

- name: ensure postgresql is installed
  apt: name="{{ item }}" state=present update_cache=yes
  with_items:
    - postgresql-9.4
    - postgresql-server-dev-9.4

- name: ensure postgresql is started
  service: name=postgresql state=started enabled=yes
