---

- name: restart sshd
  service: name=sshd state=restarted

- name: update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata

- name: sync time
  command: ntpdate pool.ntp.org
  ignore_errors: yes
