#!/bin/sh
exec 2>&1
export RAILS_ENV={{ app_env }}
USER={{ user }}
APP_ROOT={{ app_path }}
cd $APP_ROOT
exec chpst -u $USER /home/$USER/.rvm/wrappers/ruby-{{ ruby_version }}/bundle exec rake resque:work QUEUES=* TERM_CHILD=1
